var searchData=
[
  ['geometry_9308',['Geometry',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Geometry.html',1,'amrex']]],
  ['geometrydata_9309',['GeometryData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GeometryData.html',1,'amrex']]],
  ['geometryshop_9310',['GeometryShop',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1GeometryShop.html',1,'amrex::EB2']]],
  ['get_5fneighbor_5fcells_9311',['get_neighbor_cells',['https://amrex-codes.github.io/amrex/doxygen/interfaceamrex__ebcellflag__module_1_1get__neighbor__cells.html',1,'amrex_ebcellflag_module']]],
  ['getbucket_9312',['GetBucket',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GetBucket.html',1,'amrex']]],
  ['getnode_9313',['GetNode',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1nodelap__detail_1_1GetNode.html',1,'amrex::nodelap_detail']]],
  ['getnode2_9314',['GetNode2',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1nodelap__detail_1_1GetNode2.html',1,'amrex::nodelap_detail']]],
  ['getparticlebin_9315',['GetParticleBin',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GetParticleBin.html',1,'amrex']]],
  ['getpid_9316',['GetPID',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GetPID.html',1,'amrex']]],
  ['getsendbufferoffset_9317',['GetSendBufferOffset',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GetSendBufferOffset.html',1,'amrex']]],
  ['gfab_9318',['GFab',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1GFab.html',1,'amrex::EB2']]],
  ['gmres_9319',['GMRES',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GMRES.html',1,'amrex']]],
  ['gmres_3c_20mf_2c_20gmresmlmgt_3c_20mf_20_3e_20_3e_9320',['GMRES&lt; MF, GMRESMLMGT&lt; MF &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GMRES.html',1,'']]],
  ['gmresmlmgt_9321',['GMRESMLMGT',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GMRESMLMGT.html',1,'amrex']]],
  ['gpu_5ftuple_5felement_9322',['gpu_tuple_element',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__element.html',1,'amrex::detail']]],
  ['gpu_5ftuple_5felement_3c_20i_2c_20head_20_3e_9323',['gpu_tuple_element&lt; I, Head &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__element.html',1,'']]],
  ['gpu_5ftuple_5fimpl_9324',['gpu_tuple_impl',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__impl.html',1,'amrex::detail']]],
  ['gpu_5ftuple_5fimpl_3c_200_2c_20ts_2e_2e_2e_20_3e_9325',['gpu_tuple_impl&lt; 0, Ts... &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__impl.html',1,'']]],
  ['gpu_5ftuple_5fimpl_3c_20i_2b1_2c_20tail_2e_2e_2e_20_3e_9326',['gpu_tuple_impl&lt; I+1, Tail... &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__impl.html',1,'']]],
  ['gpu_5ftuple_5fimpl_3c_20i_2c_20head_20_3e_9327',['gpu_tuple_impl&lt; I, Head &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__impl_3_01I_00_01Head_01_4.html',1,'amrex::detail']]],
  ['gpu_5ftuple_5fimpl_3c_20i_2c_20head_2c_20tail_2e_2e_2e_20_3e_9328',['gpu_tuple_impl&lt; I, Head, Tail... &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__impl_3_01I_00_01Head_00_01Tail_8_8_8_01_4.html',1,'amrex::detail']]],
  ['gpuable_9329',['GPUable',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GPUable.html',1,'amrex']]],
  ['gpuarray_9330',['GpuArray',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20amrex_3a_3aalgoim_3a_3ainterval_2c_20n_20_3e_9331',['GpuArray&lt; amrex::algoim::Interval, N &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20amrex_3a_3aalgoim_3a_3aquadraturerule_3a_3anode_2c_20256_20_3e_9332',['GpuArray&lt; amrex::algoim::QuadratureRule::Node, 256 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20amrex_3a_3aeb2_3a_3apolyterm_2c_20n_20_3e_9333',['GpuArray&lt; amrex::EB2::PolyTerm, N &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20amrex_3a_3amlcelllinopt_3a_3abctl_2c_202_20_2aamrex_5fspacedim_20_3e_9334',['GpuArray&lt; amrex::MLCellLinOpT::BCTL, 2 *AMREX_SPACEDIM &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20bool_2c_20n_20_3e_9335',['GpuArray&lt; bool, N &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20const_20int_20_2a_2c_20narrayint_20_3e_9336',['GpuArray&lt; const int *, NArrayInt &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20const_20particlereal_20_2a_2c_20narrayreal_20_3e_9337',['GpuArray&lt; const ParticleReal *, NArrayReal &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20int_20_2a_2c_20nai_20_3e_9338',['GpuArray&lt; int *, NAI &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20int_2c_202_20_3e_9339',['GpuArray&lt; int, 2 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20int_2c_203_20_3e_9340',['GpuArray&lt; int, 3 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20int_2c_204_20_3e_9341',['GpuArray&lt; int, 4 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20int_2c_20amrex_5fgpu_5fmax_5fstreams_20_3e_9342',['GpuArray&lt; int, AMREX_GPU_MAX_STREAMS &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20node_2c_20256_20_3e_9343',['GpuArray&lt; Node, 256 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20particlereal_20_2a_2c_20nar_20_3e_9344',['GpuArray&lt; ParticleReal *, NAR &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20particlereal_2c_20amrex_5fspacedim_20_3e_9345',['GpuArray&lt; ParticleReal, AMREX_SPACEDIM &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20real_2c_203_20_3e_9346',['GpuArray&lt; Real, 3 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20real_2c_20amrex_5fspacedim_20_3e_9347',['GpuArray&lt; Real, AMREX_SPACEDIM &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20real_2c_20nelems_20_3e_9348',['GpuArray&lt; Real, nelems &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpuarray_3c_20real_2c_28m_2b2_29_20_2a_28m_2b1_29_2f2_20_3e_9349',['GpuArray&lt; Real,(M+2) *(M+1)/2 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'']]],
  ['gpubinpolicy_9350',['GPUBinPolicy',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1BinPolicy_1_1GPUBinPolicy.html',1,'amrex::BinPolicy']]],
  ['gpubndryfuncfab_9351',['GpuBndryFuncFab',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GpuBndryFuncFab.html',1,'amrex']]],
  ['gpucomplex_9352',['GpuComplex',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuComplex.html',1,'amrex']]],
  ['gputuple_9353',['GpuTuple',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GpuTuple.html',1,'amrex']]],
  ['gputuple_3c_20fs_2e_2e_2e_20_3e_9354',['GpuTuple&lt; Fs... &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GpuTuple.html',1,'']]],
  ['gputupleelement_9355',['GpuTupleElement',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuTupleElement.html',1,'amrex']]],
  ['gputupleelement_3c_200_2c_20gputuple_3c_20head_2c_20tail_2e_2e_2e_20_3e_20_3e_9356',['GpuTupleElement&lt; 0, GpuTuple&lt; Head, Tail... &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuTupleElement_3_010_00_01GpuTuple_3_01Head_00_01Tail_8_8_8_01_4_01_4.html',1,'amrex']]],
  ['gputupleelement_3c_20i_2c_20gputuple_3c_20head_2c_20tail_2e_2e_2e_20_3e_20_3e_9357',['GpuTupleElement&lt; I, GpuTuple&lt; Head, Tail... &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuTupleElement_3_01I_00_01GpuTuple_3_01Head_00_01Tail_8_8_8_01_4_01_4.html',1,'amrex']]],
  ['gputupleelement_3c_20i_2d1_2c_20gputuple_3c_20tail_2e_2e_2e_20_3e_20_3e_9358',['GpuTupleElement&lt; I-1, GpuTuple&lt; Tail... &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuTupleElement.html',1,'']]],
  ['gputuplesize_9359',['GpuTupleSize',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuTupleSize.html',1,'amrex']]],
  ['gputuplesize_3c_20gputuple_3c_20ts_2e_2e_2e_20_3e_20_3e_9360',['GpuTupleSize&lt; GpuTuple&lt; Ts... &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuTupleSize_3_01GpuTuple_3_01Ts_8_8_8_01_4_01_4.html',1,'amrex']]],
  ['graphsafeguard_9361',['GraphSafeGuard',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Gpu_1_1GraphSafeGuard.html',1,'amrex::Gpu']]],
  ['gridsize_9362',['GridSize',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Gpu_1_1GridSize.html',1,'amrex::Gpu']]],
  ['gshoplevel_9363',['GShopLevel',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1GShopLevel.html',1,'amrex::EB2']]],
  ['gshoplevel_3c_20chkptfile_20_3e_9364',['GShopLevel&lt; ChkptFile &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1GShopLevel.html',1,'']]],
  ['gshoplevel_3c_20stltools_20_3e_9365',['GShopLevel&lt; STLtools &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1GShopLevel.html',1,'']]]
];
