var searchData=
[
  ['packcomponents_9990',['PackComponents',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1NonLocalBC_1_1PackComponents.html',1,'amrex::NonLocalBC']]],
  ['parconstiter_5fimpl_9991',['ParConstIter_impl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParConstIter__impl.html',1,'amrex']]],
  ['parena_9992',['PArena',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PArena.html',1,'amrex']]],
  ['parforinfo_9993',['ParForInfo',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1ParForInfo.html',1,'amrex::FabArrayBase']]],
  ['pargdb_9994',['ParGDB',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParGDB.html',1,'amrex']]],
  ['pargdbbase_9995',['ParGDBBase',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParGDBBase.html',1,'amrex']]],
  ['pariter_5fimpl_9996',['ParIter_impl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParIter__impl.html',1,'amrex']]],
  ['pariterbase_5fimpl_9997',['ParIterBase_impl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParIterBase__impl.html',1,'amrex']]],
  ['parmparse_9998',['ParmParse',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParmParse.html',1,'amrex']]],
  ['parser_9999',['Parser',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Parser.html',1,'amrex']]],
  ['parser_5fassign_10000',['parser_assign',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__assign.html',1,'amrex']]],
  ['parser_5ff1_10001',['parser_f1',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__f1.html',1,'amrex']]],
  ['parser_5ff2_10002',['parser_f2',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__f2.html',1,'amrex']]],
  ['parser_5ff3_10003',['parser_f3',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__f3.html',1,'amrex']]],
  ['parser_5fnode_10004',['parser_node',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__node.html',1,'amrex']]],
  ['parser_5fnumber_10005',['parser_number',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__number.html',1,'amrex']]],
  ['parser_5fsymbol_10006',['parser_symbol',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__symbol.html',1,'amrex']]],
  ['parserexeadd_10007',['ParserExeADD',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD.html',1,'amrex']]],
  ['parserexeadd_5fpn_10008',['ParserExeADD_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__PN.html',1,'amrex']]],
  ['parserexeadd_5fpp_10009',['ParserExeADD_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__PP.html',1,'amrex']]],
  ['parserexeadd_5fvn_10010',['ParserExeADD_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__VN.html',1,'amrex']]],
  ['parserexeadd_5fvp_10011',['ParserExeADD_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__VP.html',1,'amrex']]],
  ['parserexecutor_10012',['ParserExecutor',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExecutor.html',1,'amrex']]],
  ['parserexecutor_3c_203_20_3e_10013',['ParserExecutor&lt; 3 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExecutor.html',1,'amrex']]],
  ['parserexediv_5fb_10014',['ParserExeDIV_B',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__B.html',1,'amrex']]],
  ['parserexediv_5ff_10015',['ParserExeDIV_F',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__F.html',1,'amrex']]],
  ['parserexediv_5fpn_10016',['ParserExeDIV_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__PN.html',1,'amrex']]],
  ['parserexediv_5fpp_10017',['ParserExeDIV_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__PP.html',1,'amrex']]],
  ['parserexediv_5fvn_10018',['ParserExeDIV_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__VN.html',1,'amrex']]],
  ['parserexediv_5fvp_10019',['ParserExeDIV_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__VP.html',1,'amrex']]],
  ['parserexef1_10020',['ParserExeF1',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeF1.html',1,'amrex']]],
  ['parserexef2_5fb_10021',['ParserExeF2_B',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeF2__B.html',1,'amrex']]],
  ['parserexef2_5ff_10022',['ParserExeF2_F',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeF2__F.html',1,'amrex']]],
  ['parserexeif_10023',['ParserExeIF',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeIF.html',1,'amrex']]],
  ['parserexejump_10024',['ParserExeJUMP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeJUMP.html',1,'amrex']]],
  ['parserexemul_10025',['ParserExeMUL',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL.html',1,'amrex']]],
  ['parserexemul_5fpn_10026',['ParserExeMUL_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__PN.html',1,'amrex']]],
  ['parserexemul_5fpp_10027',['ParserExeMUL_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__PP.html',1,'amrex']]],
  ['parserexemul_5fvn_10028',['ParserExeMUL_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__VN.html',1,'amrex']]],
  ['parserexemul_5fvp_10029',['ParserExeMUL_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__VP.html',1,'amrex']]],
  ['parserexenull_10030',['ParserExeNull',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeNull.html',1,'amrex']]],
  ['parserexenumber_10031',['ParserExeNumber',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeNumber.html',1,'amrex']]],
  ['parserexepowi_10032',['ParserExePOWI',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExePOWI.html',1,'amrex']]],
  ['parserexesquare_10033',['ParserExeSquare',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSquare.html',1,'amrex']]],
  ['parserexesub_5fb_10034',['ParserExeSUB_B',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__B.html',1,'amrex']]],
  ['parserexesub_5ff_10035',['ParserExeSUB_F',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__F.html',1,'amrex']]],
  ['parserexesub_5fpn_10036',['ParserExeSUB_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__PN.html',1,'amrex']]],
  ['parserexesub_5fpp_10037',['ParserExeSUB_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__PP.html',1,'amrex']]],
  ['parserexesub_5fvn_10038',['ParserExeSUB_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__VN.html',1,'amrex']]],
  ['parserexesub_5fvp_10039',['ParserExeSUB_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__VP.html',1,'amrex']]],
  ['parserexesymbol_10040',['ParserExeSymbol',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSymbol.html',1,'amrex']]],
  ['parserif_10041',['ParserIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1ParserIF.html',1,'amrex::EB2']]],
  ['particle_10042',['Particle',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Particle.html',1,'amrex']]],
  ['particlearray_10043',['ParticleArray',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleArray.html',1,'amrex']]],
  ['particlearrayaccessor_10044',['ParticleArrayAccessor',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleArrayAccessor.html',1,'amrex']]],
  ['particlebase_10045',['ParticleBase',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase.html',1,'amrex']]],
  ['particlebase_3c_20t_2c_200_2c_200_20_3e_10046',['ParticleBase&lt; T, 0, 0 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase_3_01T_00_010_00_010_01_4.html',1,'amrex']]],
  ['particlebase_3c_20t_2c_200_2c_20nint_20_3e_10047',['ParticleBase&lt; T, 0, NInt &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase_3_01T_00_010_00_01NInt_01_4.html',1,'amrex']]],
  ['particlebase_3c_20t_2c_20nreal_2c_200_20_3e_10048',['ParticleBase&lt; T, NReal, 0 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase_3_01T_00_01NReal_00_010_01_4.html',1,'amrex']]],
  ['particlebuffermap_10049',['ParticleBufferMap',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleBufferMap.html',1,'amrex']]],
  ['particlecommdata_10050',['ParticleCommData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCommData.html',1,'amrex']]],
  ['particlecontainer_5fimpl_10051',['ParticleContainer_impl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleContainer__impl.html',1,'amrex']]],
  ['particlecontainerbase_10052',['ParticleContainerBase',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleContainerBase.html',1,'amrex']]],
  ['particlecopyop_10053',['ParticleCopyOp',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCopyOp.html',1,'amrex']]],
  ['particlecopyplan_10054',['ParticleCopyPlan',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCopyPlan.html',1,'amrex']]],
  ['particlecpuwrapper_10055',['ParticleCPUWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCPUWrapper.html',1,'amrex']]],
  ['particleidwrapper_10056',['ParticleIDWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleIDWrapper.html',1,'amrex']]],
  ['particleinittype_10057',['ParticleInitType',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleInitType.html',1,'amrex']]],
  ['particlelocator_10058',['ParticleLocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleLocator.html',1,'amrex']]],
  ['particlelocdata_10059',['ParticleLocData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleLocData.html',1,'amrex']]],
  ['particletile_10060',['ParticleTile',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleTile.html',1,'amrex']]],
  ['particletiledata_10061',['ParticleTileData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleTileData.html',1,'amrex']]],
  ['particletiledata_3c_20soaparticlebase_2c_20narrayreal_2c_20narrayint_20_3e_10062',['ParticleTileData&lt; SoAParticleBase, NArrayReal, NArrayInt &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleTileData.html',1,'amrex']]],
  ['pcdata_10063',['PCData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'amrex']]],
  ['pcinterp_10064',['PCInterp',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PCInterp.html',1,'amrex']]],
  ['periodicity_10065',['Periodicity',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Periodicity.html',1,'amrex']]],
  ['persistentifstream_10066',['PersistentIFStream',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1VisMF_1_1PersistentIFStream.html',1,'amrex::VisMF']]],
  ['petscabeclap_10067',['PETScABecLap',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PETScABecLap.html',1,'amrex']]],
  ['physbcfunct_10068',['PhysBCFunct',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PhysBCFunct.html',1,'amrex']]],
  ['physbcfunctnoop_10069',['PhysBCFunctNoOp',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PhysBCFunctNoOp.html',1,'amrex']]],
  ['physbcfunctusecoarseghost_10070',['PhysBCFunctUseCoarseGhost',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PhysBCFunctUseCoarseGhost.html',1,'amrex']]],
  ['pinned_10071',['Pinned',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Gpu_1_1Pinned.html',1,'amrex::Gpu']]],
  ['pinnedarenaallocator_10072',['PinnedArenaAllocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PinnedArenaAllocator.html',1,'amrex']]],
  ['pinnedarenawrapper_10073',['PinnedArenaWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PinnedArenaWrapper.html',1,'amrex']]],
  ['plan_10074',['Plan',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FFT_1_1Plan.html',1,'amrex::FFT']]],
  ['plan_3c_20t_20_3e_10075',['Plan&lt; T &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FFT_1_1Plan.html',1,'amrex::FFT']]],
  ['planeif_10076',['PlaneIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PlaneIF.html',1,'amrex::EB2']]],
  ['plotfiledata_10077',['PlotFileData',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PlotFileData.html',1,'amrex']]],
  ['plotfiledataimpl_10078',['PlotFileDataImpl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PlotFileDataImpl.html',1,'amrex']]],
  ['plus_10079',['Plus',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Plus.html',1,'amrex']]],
  ['podvector_10080',['PODVector',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3aarray4_3c_20real_20const_20_3e_20_3e_10081',['PODVector&lt; amrex::Array4&lt; Real const &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3aassigngrid_3c_20biniteratorfactory_20_3e_20_3e_10082',['PODVector&lt; amrex::AssignGrid&lt; BinIteratorFactory &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3aboxnd_20_3e_10083',['PODVector&lt; amrex::BoxND &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3agpuarray_3c_20amrex_3a_3amlcelllinopt_3a_3abctl_2c_202_20_2aamrex_5fspacedim_20_3e_20_3e_10084',['PODVector&lt; amrex::GpuArray&lt; amrex::MLCellLinOpT::BCTL, 2 *AMREX_SPACEDIM &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3aneighborcode_20_3e_10085',['PODVector&lt; amrex::NeighborCode &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3aopenbc_3a_3amomtag_20_3e_10086',['PODVector&lt; amrex::openbc::MomTag &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3astltools_3a_3atriangle_20_3e_10087',['PODVector&lt; amrex::STLtools::Triangle &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3axdim3_20_3e_10088',['PODVector&lt; amrex::XDim3 &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20char_20_3e_10089',['PODVector&lt; char &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20char_2c_20amrex_3a_3apolymorphicarenaallocator_3c_20char_20_3e_20_3e_10090',['PODVector&lt; char, amrex::PolymorphicArenaAllocator&lt; char &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20const_20int_20_2a_20_3e_10091',['PODVector&lt; const int * &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20const_20int_20_2a_2c_20allocator_3c_20const_20int_20_2a_20_3e_20_3e_10092',['PODVector&lt; const int *, Allocator&lt; const int * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20const_20particlereal_20_2a_20_3e_10093',['PODVector&lt; const ParticleReal * &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20const_20particlereal_20_2a_2c_20allocator_3c_20const_20particlereal_20_2a_20_3e_20_3e_10094',['PODVector&lt; const ParticleReal *, Allocator&lt; const ParticleReal * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20index_5ftype_20_3e_10095',['PODVector&lt; index_type &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20int_20_2a_20_3e_10096',['PODVector&lt; int * &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20int_20_2a_2c_20allocator_3c_20int_20_2a_20_3e_20_3e_10097',['PODVector&lt; int *, Allocator&lt; int * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20int_20_3e_10098',['PODVector&lt; int &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20long_20_3e_10099',['PODVector&lt; Long &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20node_20_3e_10100',['PODVector&lt; Node &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20particlereal_20_2a_20_3e_10101',['PODVector&lt; ParticleReal * &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20particlereal_20_2a_2c_20allocator_3c_20particlereal_20_2a_20_3e_20_3e_10102',['PODVector&lt; ParticleReal *, Allocator&lt; ParticleReal * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20particletype_2c_20allocator_3c_20particletype_20_3e_20_3e_10103',['PODVector&lt; ParticleType, Allocator&lt; ParticleType &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20std_3a_3asize_5ft_20_3e_10104',['PODVector&lt; std::size_t &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20t_2c_20allocator_20_3e_10105',['PODVector&lt; T, Allocator &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20uint64_5ft_2c_20allocator_3c_20uint64_5ft_20_3e_20_3e_10106',['PODVector&lt; uint64_t, Allocator&lt; uint64_t &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20unsigned_20int_20_3e_10107',['PODVector&lt; unsigned int &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['poisson_10108',['Poisson',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1FFT_1_1Poisson.html',1,'amrex::FFT']]],
  ['poisson_3c_20amrex_3a_3amultifab_20_3e_10109',['Poisson&lt; amrex::MultiFab &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1FFT_1_1Poisson.html',1,'amrex::FFT']]],
  ['poissonhybrid_10110',['PoissonHybrid',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1FFT_1_1PoissonHybrid.html',1,'amrex::FFT']]],
  ['polarb_10111',['PolarB',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1PolarB.html',1,'amrex::FabArrayBase']]],
  ['poly_5feval_10112',['poly_eval',['https://amrex-codes.github.io/amrex/doxygen/interfacesdcquadrature__mod_1_1poly__eval.html',1,'sdcquadrature_mod']]],
  ['polyif_10113',['PolyIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PolyIF.html',1,'amrex::EB2']]],
  ['polymorphicarenaallocator_10114',['PolymorphicArenaAllocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PolymorphicArenaAllocator.html',1,'amrex']]],
  ['polymorphicarenawrapper_10115',['PolymorphicArenaWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PolymorphicArenaWrapper.html',1,'amrex']]],
  ['polymorphicarray4_10116',['PolymorphicArray4',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PolymorphicArray4.html',1,'amrex']]],
  ['polynomialif_10117',['PolynomialIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PolynomialIF.html',1,'amrex::EB2']]],
  ['polyterm_10118',['PolyTerm',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PolyTerm.html',1,'amrex::EB2']]],
  ['poststagenoop_10119',['PostStageNoOp',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RungeKutta_1_1PostStageNoOp.html',1,'amrex::RungeKutta']]],
  ['pp_5fentry_10120',['PP_entry',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParmParse_1_1PP__entry.html',1,'amrex::ParmParse']]],
  ['print_10121',['Print',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Print.html',1,'amrex']]],
  ['printtofile_10122',['PrintToFile',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PrintToFile.html',1,'amrex']]],
  ['processteam_10123',['ProcessTeam',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParallelDescriptor_1_1ProcessTeam.html',1,'amrex::ParallelDescriptor']]],
  ['procstats_10124',['ProcStats',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1TinyProfiler_1_1ProcStats.html',1,'amrex::TinyProfiler']]],
  ['psicode_10125',['PsiCode',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1algoim_1_1PsiCode.html',1,'amrex::algoim']]]
];
