var searchData=
[
  ['packcomponents_0',['PackComponents',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1NonLocalBC_1_1PackComponents.html',1,'amrex::NonLocalBC']]],
  ['parconstiter_5fimpl_1',['ParConstIter_impl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParConstIter__impl.html',1,'amrex']]],
  ['parena_2',['PArena',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PArena.html',1,'amrex']]],
  ['parforinfo_3',['ParForInfo',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1ParForInfo.html',1,'amrex::FabArrayBase']]],
  ['pargdb_4',['ParGDB',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParGDB.html',1,'amrex']]],
  ['pargdbbase_5',['ParGDBBase',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParGDBBase.html',1,'amrex']]],
  ['pariter_5fimpl_6',['ParIter_impl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParIter__impl.html',1,'amrex']]],
  ['pariterbase_5fimpl_7',['ParIterBase_impl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParIterBase__impl.html',1,'amrex']]],
  ['parmparse_8',['ParmParse',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParmParse.html',1,'amrex']]],
  ['parser_9',['Parser',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Parser.html',1,'amrex']]],
  ['parser_5fassign_10',['parser_assign',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__assign.html',1,'amrex']]],
  ['parser_5ff1_11',['parser_f1',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__f1.html',1,'amrex']]],
  ['parser_5ff2_12',['parser_f2',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__f2.html',1,'amrex']]],
  ['parser_5ff3_13',['parser_f3',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__f3.html',1,'amrex']]],
  ['parser_5fnode_14',['parser_node',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__node.html',1,'amrex']]],
  ['parser_5fnumber_15',['parser_number',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__number.html',1,'amrex']]],
  ['parser_5fsymbol_16',['parser_symbol',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__symbol.html',1,'amrex']]],
  ['parser_5fusrf1_17',['parser_usrf1',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__usrf1.html',1,'amrex']]],
  ['parser_5fusrf2_18',['parser_usrf2',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__usrf2.html',1,'amrex']]],
  ['parser_5fusrfn_19',['parser_usrfn',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__usrfn.html',1,'amrex']]],
  ['parserexeadd_20',['ParserExeADD',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD.html',1,'amrex']]],
  ['parserexeadd_5fpn_21',['ParserExeADD_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__PN.html',1,'amrex']]],
  ['parserexeadd_5fpp_22',['ParserExeADD_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__PP.html',1,'amrex']]],
  ['parserexeadd_5fvn_23',['ParserExeADD_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__VN.html',1,'amrex']]],
  ['parserexeadd_5fvp_24',['ParserExeADD_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__VP.html',1,'amrex']]],
  ['parserexecutor_25',['ParserExecutor',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExecutor.html',1,'amrex']]],
  ['parserexecutor_3c_203_20_3e_26',['ParserExecutor&lt; 3 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExecutor.html',1,'amrex']]],
  ['parserexecutor_3c_204_20_3e_27',['ParserExecutor&lt; 4 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExecutor.html',1,'amrex']]],
  ['parserexediv_5fb_28',['ParserExeDIV_B',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__B.html',1,'amrex']]],
  ['parserexediv_5ff_29',['ParserExeDIV_F',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__F.html',1,'amrex']]],
  ['parserexediv_5fpn_30',['ParserExeDIV_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__PN.html',1,'amrex']]],
  ['parserexediv_5fpp_31',['ParserExeDIV_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__PP.html',1,'amrex']]],
  ['parserexediv_5fvn_32',['ParserExeDIV_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__VN.html',1,'amrex']]],
  ['parserexediv_5fvp_33',['ParserExeDIV_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__VP.html',1,'amrex']]],
  ['parserexef1_34',['ParserExeF1',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeF1.html',1,'amrex']]],
  ['parserexef2_5fb_35',['ParserExeF2_B',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeF2__B.html',1,'amrex']]],
  ['parserexef2_5ff_36',['ParserExeF2_F',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeF2__F.html',1,'amrex']]],
  ['parserexeif_37',['ParserExeIF',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeIF.html',1,'amrex']]],
  ['parserexejump_38',['ParserExeJUMP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeJUMP.html',1,'amrex']]],
  ['parserexemul_39',['ParserExeMUL',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL.html',1,'amrex']]],
  ['parserexemul_5fpn_40',['ParserExeMUL_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__PN.html',1,'amrex']]],
  ['parserexemul_5fpp_41',['ParserExeMUL_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__PP.html',1,'amrex']]],
  ['parserexemul_5fvn_42',['ParserExeMUL_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__VN.html',1,'amrex']]],
  ['parserexemul_5fvp_43',['ParserExeMUL_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__VP.html',1,'amrex']]],
  ['parserexenull_44',['ParserExeNull',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeNull.html',1,'amrex']]],
  ['parserexenumber_45',['ParserExeNumber',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeNumber.html',1,'amrex']]],
  ['parserexepowi_46',['ParserExePOWI',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExePOWI.html',1,'amrex']]],
  ['parserexesquare_47',['ParserExeSquare',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSquare.html',1,'amrex']]],
  ['parserexesub_5fb_48',['ParserExeSUB_B',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__B.html',1,'amrex']]],
  ['parserexesub_5ff_49',['ParserExeSUB_F',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__F.html',1,'amrex']]],
  ['parserexesub_5fpn_50',['ParserExeSUB_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__PN.html',1,'amrex']]],
  ['parserexesub_5fpp_51',['ParserExeSUB_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__PP.html',1,'amrex']]],
  ['parserexesub_5fvn_52',['ParserExeSUB_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__VN.html',1,'amrex']]],
  ['parserexesub_5fvp_53',['ParserExeSUB_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__VP.html',1,'amrex']]],
  ['parserexesymbol_54',['ParserExeSymbol',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSymbol.html',1,'amrex']]],
  ['parserexeuserfn_55',['ParserExeUserFn',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeUserFn.html',1,'amrex']]],
  ['parserif_56',['ParserIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1ParserIF.html',1,'amrex::EB2']]],
  ['particle_57',['Particle',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Particle.html',1,'amrex']]],
  ['particlearray_58',['ParticleArray',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleArray.html',1,'amrex']]],
  ['particlearrayaccessor_59',['ParticleArrayAccessor',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleArrayAccessor.html',1,'amrex']]],
  ['particlebase_60',['ParticleBase',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase.html',1,'amrex']]],
  ['particlebase_3c_20t_2c_200_2c_200_20_3e_61',['ParticleBase&lt; T, 0, 0 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase_3_01T_00_010_00_010_01_4.html',1,'amrex']]],
  ['particlebase_3c_20t_2c_200_2c_20nint_20_3e_62',['ParticleBase&lt; T, 0, NInt &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase_3_01T_00_010_00_01NInt_01_4.html',1,'amrex']]],
  ['particlebase_3c_20t_2c_20nreal_2c_200_20_3e_63',['ParticleBase&lt; T, NReal, 0 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase_3_01T_00_01NReal_00_010_01_4.html',1,'amrex']]],
  ['particlebuffermap_64',['ParticleBufferMap',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleBufferMap.html',1,'amrex']]],
  ['particlecommdata_65',['ParticleCommData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCommData.html',1,'amrex']]],
  ['particlecontainer_5fimpl_66',['ParticleContainer_impl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleContainer__impl.html',1,'amrex']]],
  ['particlecontainerbase_67',['ParticleContainerBase',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleContainerBase.html',1,'amrex']]],
  ['particlecopyop_68',['ParticleCopyOp',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCopyOp.html',1,'amrex']]],
  ['particlecopyplan_69',['ParticleCopyPlan',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCopyPlan.html',1,'amrex']]],
  ['particlecpuwrapper_70',['ParticleCPUWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCPUWrapper.html',1,'amrex']]],
  ['particleidwrapper_71',['ParticleIDWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleIDWrapper.html',1,'amrex']]],
  ['particleinittype_72',['ParticleInitType',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleInitType.html',1,'amrex']]],
  ['particlelocator_73',['ParticleLocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleLocator.html',1,'amrex']]],
  ['particlelocdata_74',['ParticleLocData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleLocData.html',1,'amrex']]],
  ['particletile_75',['ParticleTile',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleTile.html',1,'amrex']]],
  ['particletiledata_76',['ParticleTileData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleTileData.html',1,'amrex']]],
  ['particletiledata_3c_20soaparticlebase_2c_20narrayreal_2c_20narrayint_20_3e_77',['ParticleTileData&lt; SoAParticleBase, NArrayReal, NArrayInt &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleTileData.html',1,'amrex']]],
  ['pcdata_78',['PCData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'amrex']]],
  ['pcdata_3c_20fab_20_3e_79',['PCData&lt; FAB &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'amrex']]],
  ['pcinterp_80',['PCInterp',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PCInterp.html',1,'amrex']]],
  ['periodicity_81',['Periodicity',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Periodicity.html',1,'amrex']]],
  ['persistentifstream_82',['PersistentIFStream',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1VisMF_1_1PersistentIFStream.html',1,'amrex::VisMF']]],
  ['petscabeclap_83',['PETScABecLap',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PETScABecLap.html',1,'amrex']]],
  ['physbcfunct_84',['PhysBCFunct',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PhysBCFunct.html',1,'amrex']]],
  ['physbcfunctnoop_85',['PhysBCFunctNoOp',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PhysBCFunctNoOp.html',1,'amrex']]],
  ['physbcfunctusecoarseghost_86',['PhysBCFunctUseCoarseGhost',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PhysBCFunctUseCoarseGhost.html',1,'amrex']]],
  ['pinned_87',['Pinned',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Gpu_1_1Pinned.html',1,'amrex::Gpu']]],
  ['pinnedarenaallocator_88',['PinnedArenaAllocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PinnedArenaAllocator.html',1,'amrex']]],
  ['pinnedarenawrapper_89',['PinnedArenaWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PinnedArenaWrapper.html',1,'amrex']]],
  ['plan_90',['Plan',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FFT_1_1Plan.html',1,'amrex::FFT']]],
  ['plan_3c_20t_20_3e_91',['Plan&lt; T &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FFT_1_1Plan.html',1,'amrex::FFT']]],
  ['planeif_92',['PlaneIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PlaneIF.html',1,'amrex::EB2']]],
  ['plotfiledata_93',['PlotFileData',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PlotFileData.html',1,'amrex']]],
  ['plotfiledataimpl_94',['PlotFileDataImpl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PlotFileDataImpl.html',1,'amrex']]],
  ['plus_95',['Plus',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Plus.html',1,'amrex']]],
  ['podvector_96',['PODVector',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3aarray4_3c_20real_20const_20_3e_20_3e_97',['PODVector&lt; amrex::Array4&lt; Real const &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3aassigngrid_3c_20biniteratorfactory_20_3e_20_3e_98',['PODVector&lt; amrex::AssignGrid&lt; BinIteratorFactory &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3aboxnd_20_3e_99',['PODVector&lt; amrex::BoxND &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3agpuarray_3c_20amrex_3a_3amlcelllinopt_3a_3abctl_2c_202_20_2a3_20_3e_20_3e_100',['PODVector&lt; amrex::GpuArray&lt; amrex::MLCellLinOpT::BCTL, 2 *3 &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3aneighborcode_20_3e_101',['PODVector&lt; amrex::NeighborCode &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3aopenbc_3a_3amomtag_20_3e_102',['PODVector&lt; amrex::openbc::MomTag &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3axdim3_20_3e_103',['PODVector&lt; amrex::XDim3 &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20char_20_3e_104',['PODVector&lt; char &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20char_2c_20amrex_3a_3apolymorphicarenaallocator_3c_20char_20_3e_20_3e_105',['PODVector&lt; char, amrex::PolymorphicArenaAllocator&lt; char &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20const_20int_20_2a_20_3e_106',['PODVector&lt; const int * &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20const_20int_20_2a_2c_20allocator_3c_20const_20int_20_2a_20_3e_20_3e_107',['PODVector&lt; const int *, Allocator&lt; const int * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20const_20particlereal_20_2a_20_3e_108',['PODVector&lt; const ParticleReal * &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20const_20particlereal_20_2a_2c_20allocator_3c_20const_20particlereal_20_2a_20_3e_20_3e_109',['PODVector&lt; const ParticleReal *, Allocator&lt; const ParticleReal * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20index_5ftype_20_3e_110',['PODVector&lt; index_type &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20int_20_2a_20_3e_111',['PODVector&lt; int * &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20int_20_2a_2c_20allocator_3c_20int_20_2a_20_3e_20_3e_112',['PODVector&lt; int *, Allocator&lt; int * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20int_20_3e_113',['PODVector&lt; int &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20long_20_3e_114',['PODVector&lt; Long &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20node_20_3e_115',['PODVector&lt; Node &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20particlereal_20_2a_20_3e_116',['PODVector&lt; ParticleReal * &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20particlereal_20_2a_2c_20allocator_3c_20particlereal_20_2a_20_3e_20_3e_117',['PODVector&lt; ParticleReal *, Allocator&lt; ParticleReal * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20particletype_2c_20allocator_3c_20particletype_20_3e_20_3e_118',['PODVector&lt; ParticleType, Allocator&lt; ParticleType &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20std_3a_3asize_5ft_20_3e_119',['PODVector&lt; std::size_t &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20t_20_3e_120',['PODVector&lt; T &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20t_2c_20allocator_20_3e_121',['PODVector&lt; T, Allocator &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20triangle_20_3e_122',['PODVector&lt; Triangle &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20uint64_5ft_2c_20allocator_3c_20uint64_5ft_20_3e_20_3e_123',['PODVector&lt; uint64_t, Allocator&lt; uint64_t &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20unsigned_20int_20_3e_124',['PODVector&lt; unsigned int &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['poisson_125',['Poisson',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1FFT_1_1Poisson.html',1,'amrex::FFT']]],
  ['poisson_3c_20amrex_3a_3amultifab_20_3e_126',['Poisson&lt; amrex::MultiFab &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1FFT_1_1Poisson.html',1,'amrex::FFT']]],
  ['poissonhybrid_127',['PoissonHybrid',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1FFT_1_1PoissonHybrid.html',1,'amrex::FFT']]],
  ['poissonopenbc_128',['PoissonOpenBC',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1FFT_1_1PoissonOpenBC.html',1,'amrex::FFT']]],
  ['polarb_129',['PolarB',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1PolarB.html',1,'amrex::FabArrayBase']]],
  ['polyif_130',['PolyIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PolyIF.html',1,'amrex::EB2']]],
  ['polymorphicarenaallocator_131',['PolymorphicArenaAllocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PolymorphicArenaAllocator.html',1,'amrex']]],
  ['polymorphicarenawrapper_132',['PolymorphicArenaWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PolymorphicArenaWrapper.html',1,'amrex']]],
  ['polymorphicarray4_133',['PolymorphicArray4',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PolymorphicArray4.html',1,'amrex']]],
  ['polynomialif_134',['PolynomialIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PolynomialIF.html',1,'amrex::EB2']]],
  ['polyterm_135',['PolyTerm',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PolyTerm.html',1,'amrex::EB2']]],
  ['poststagenoop_136',['PostStageNoOp',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RungeKutta_1_1PostStageNoOp.html',1,'amrex::RungeKutta']]],
  ['pp_5fentry_137',['PP_entry',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParmParse_1_1PP__entry.html',1,'amrex::ParmParse']]],
  ['print_138',['Print',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Print.html',1,'amrex']]],
  ['printtofile_139',['PrintToFile',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PrintToFile.html',1,'amrex']]],
  ['processteam_140',['ProcessTeam',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParallelDescriptor_1_1ProcessTeam.html',1,'amrex::ParallelDescriptor']]],
  ['procstats_141',['ProcStats',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1TinyProfiler_1_1ProcStats.html',1,'amrex::TinyProfiler']]],
  ['psicode_142',['PsiCode',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1algoim_1_1PsiCode.html',1,'amrex::algoim']]]
];
