var searchData=
[
  ['geometry_9650',['Geometry',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Geometry.html',1,'amrex']]],
  ['geometrydata_9651',['GeometryData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GeometryData.html',1,'amrex']]],
  ['geometryshop_9652',['GeometryShop',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1GeometryShop.html',1,'amrex::EB2']]],
  ['get_5fneighbor_5fcells_9653',['get_neighbor_cells',['https://amrex-codes.github.io/amrex/doxygen/interfaceamrex__ebcellflag__module_1_1get__neighbor__cells.html',1,'amrex_ebcellflag_module']]],
  ['getbucket_9654',['GetBucket',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GetBucket.html',1,'amrex']]],
  ['getparticlebin_9655',['GetParticleBin',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GetParticleBin.html',1,'amrex']]],
  ['getpid_9656',['GetPID',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GetPID.html',1,'amrex']]],
  ['getsendbufferoffset_9657',['GetSendBufferOffset',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GetSendBufferOffset.html',1,'amrex']]],
  ['gfab_9658',['GFab',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1GFab.html',1,'amrex::EB2']]],
  ['gmres_9659',['GMRES',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GMRES.html',1,'amrex']]],
  ['gmres_3c_20mf_2c_20gmresmlmgt_3c_20mf_20_3e_20_3e_9660',['GMRES&lt; MF, GMRESMLMGT&lt; MF &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GMRES.html',1,'amrex']]],
  ['gmres_3c_20vec_2c_20gmres_5fmv_3c_20t_20_3e_20_3e_9661',['GMRES&lt; VEC, GMRES_MV&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GMRES.html',1,'amrex']]],
  ['gmres_5fmv_9662',['GMRES_MV',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GMRES__MV.html',1,'amrex']]],
  ['gmresmlmgt_9663',['GMRESMLMGT',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GMRESMLMGT.html',1,'amrex']]],
  ['gpu_5ftuple_5felement_9664',['gpu_tuple_element',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__element.html',1,'amrex::detail']]],
  ['gpu_5ftuple_5felement_3c_20i_2c_20head_20_3e_9665',['gpu_tuple_element&lt; I, Head &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__element.html',1,'amrex::detail']]],
  ['gpu_5ftuple_5fimpl_9666',['gpu_tuple_impl',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__impl.html',1,'amrex::detail']]],
  ['gpu_5ftuple_5fimpl_3c_20i_2b1_2c_20tail_2e_2e_2e_20_3e_9667',['gpu_tuple_impl&lt; I+1, Tail... &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__impl.html',1,'amrex::detail']]],
  ['gpu_5ftuple_5fimpl_3c_20i_2c_20head_20_3e_9668',['gpu_tuple_impl&lt; I, Head &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__impl_3_01I_00_01Head_01_4.html',1,'amrex::detail']]],
  ['gpu_5ftuple_5fimpl_3c_20i_2c_20head_2c_20tail_2e_2e_2e_20_3e_9669',['gpu_tuple_impl&lt; I, Head, Tail... &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1detail_1_1gpu__tuple__impl_3_01I_00_01Head_00_01Tail_8_8_8_01_4.html',1,'amrex::detail']]],
  ['gpuable_9670',['GPUable',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GPUable.html',1,'amrex']]],
  ['gpuarray_9671',['GpuArray',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20amrex_3a_3aalgoim_3a_3ainterval_2c_20n_20_3e_9672',['GpuArray&lt; amrex::algoim::Interval, N &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20amrex_3a_3aeb2_3a_3apolyterm_2c_20n_20_3e_9673',['GpuArray&lt; amrex::EB2::PolyTerm, N &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20bool_2c_20n_20_3e_9674',['GpuArray&lt; bool, N &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20const_20int_20_2a_2c_20narrayint_20_3e_9675',['GpuArray&lt; const int *, NArrayInt &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20const_20particlereal_20_2a_2c_20narrayreal_20_3e_9676',['GpuArray&lt; const ParticleReal *, NArrayReal &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20int_20_2a_2c_20nai_20_3e_9677',['GpuArray&lt; int *, NAI &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20int_2c_202_20_3e_9678',['GpuArray&lt; int, 2 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20int_2c_203_20_3e_9679',['GpuArray&lt; int, 3 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20int_2c_204_20_3e_9680',['GpuArray&lt; int, 4 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20int_2c_20amrex_5fgpu_5fmax_5fstreams_20_3e_9681',['GpuArray&lt; int, AMREX_GPU_MAX_STREAMS &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20node_2c_20256_20_3e_9682',['GpuArray&lt; Node, 256 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20particlereal_20_2a_2c_20nar_20_3e_9683',['GpuArray&lt; ParticleReal *, NAR &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20particlereal_2c_20amrex_5fspacedim_20_3e_9684',['GpuArray&lt; ParticleReal, AMREX_SPACEDIM &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20real_2c_203_20_3e_9685',['GpuArray&lt; Real, 3 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20real_2c_20amrex_5fspacedim_20_3e_9686',['GpuArray&lt; Real, AMREX_SPACEDIM &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20real_2c_20nelems_20_3e_9687',['GpuArray&lt; Real, nelems &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpuarray_3c_20real_2c_28m_2b2_29_20_2a_28m_2b1_29_2f2_20_3e_9688',['GpuArray&lt; Real,(M+2) *(M+1)/2 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex']]],
  ['gpubinpolicy_9689',['GPUBinPolicy',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1BinPolicy_1_1GPUBinPolicy.html',1,'amrex::BinPolicy']]],
  ['gpubndryfuncfab_9690',['GpuBndryFuncFab',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GpuBndryFuncFab.html',1,'amrex']]],
  ['gpucomplex_9691',['GpuComplex',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuComplex.html',1,'amrex']]],
  ['gpucomplex_3c_20t_20_3e_9692',['GpuComplex&lt; T &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuComplex.html',1,'amrex']]],
  ['gputuple_9693',['GpuTuple',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GpuTuple.html',1,'amrex']]],
  ['gputuple_3c_20fs_2e_2e_2e_20_3e_9694',['GpuTuple&lt; Fs... &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1GpuTuple.html',1,'amrex']]],
  ['gputupleelement_9695',['GpuTupleElement',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuTupleElement.html',1,'amrex']]],
  ['gputupleelement_3c_200_2c_20gputuple_3c_20head_2c_20tail_2e_2e_2e_20_3e_20_3e_9696',['GpuTupleElement&lt; 0, GpuTuple&lt; Head, Tail... &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuTupleElement_3_010_00_01GpuTuple_3_01Head_00_01Tail_8_8_8_01_4_01_4.html',1,'amrex']]],
  ['gputupleelement_3c_20i_2c_20gputuple_3c_20head_2c_20tail_2e_2e_2e_20_3e_20_3e_9697',['GpuTupleElement&lt; I, GpuTuple&lt; Head, Tail... &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuTupleElement_3_01I_00_01GpuTuple_3_01Head_00_01Tail_8_8_8_01_4_01_4.html',1,'amrex']]],
  ['gputupleelement_3c_20i_2d1_2c_20gputuple_3c_20tail_2e_2e_2e_20_3e_20_3e_9698',['GpuTupleElement&lt; I-1, GpuTuple&lt; Tail... &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuTupleElement.html',1,'amrex']]],
  ['gputuplesize_9699',['GpuTupleSize',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuTupleSize.html',1,'amrex']]],
  ['gputuplesize_3c_20gputuple_3c_20ts_2e_2e_2e_20_3e_20_3e_9700',['GpuTupleSize&lt; GpuTuple&lt; Ts... &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuTupleSize_3_01GpuTuple_3_01Ts_8_8_8_01_4_01_4.html',1,'amrex']]],
  ['graphsafeguard_9701',['GraphSafeGuard',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Gpu_1_1GraphSafeGuard.html',1,'amrex::Gpu']]],
  ['gridsize_9702',['GridSize',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Gpu_1_1GridSize.html',1,'amrex::Gpu']]],
  ['gshoplevel_9703',['GShopLevel',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1GShopLevel.html',1,'amrex::EB2']]],
  ['gshoplevel_3c_20chkptfile_20_3e_9704',['GShopLevel&lt; ChkptFile &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1GShopLevel.html',1,'amrex::EB2']]],
  ['gshoplevel_3c_20stltools_20_3e_9705',['GShopLevel&lt; STLtools &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1GShopLevel.html',1,'amrex::EB2']]]
];
