var searchData=
[
  ['packcomponents_9895',['PackComponents',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1NonLocalBC_1_1PackComponents.html',1,'amrex::NonLocalBC']]],
  ['parconstiter_5fimpl_9896',['ParConstIter_impl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParConstIter__impl.html',1,'amrex']]],
  ['parena_9897',['PArena',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PArena.html',1,'amrex']]],
  ['parforinfo_9898',['ParForInfo',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1ParForInfo.html',1,'amrex::FabArrayBase']]],
  ['pargdb_9899',['ParGDB',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParGDB.html',1,'amrex']]],
  ['pargdbbase_9900',['ParGDBBase',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParGDBBase.html',1,'amrex']]],
  ['pariter_5fimpl_9901',['ParIter_impl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParIter__impl.html',1,'amrex']]],
  ['pariterbase_5fimpl_9902',['ParIterBase_impl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParIterBase__impl.html',1,'amrex']]],
  ['pariterbase_5fimpl_3c_20false_2c_20t_5fparticletype_2c_200_2c_200_2c_20defaultallocator_2c_20defaultassignor_20_3e_9903',['ParIterBase_impl&lt; false, T_ParticleType, 0, 0, DefaultAllocator, DefaultAssignor &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParIterBase__impl.html',1,'']]],
  ['pariterbase_5fimpl_3c_20true_2c_20t_5fparticletype_2c_200_2c_200_2c_20defaultallocator_2c_20defaultassignor_20_3e_9904',['ParIterBase_impl&lt; true, T_ParticleType, 0, 0, DefaultAllocator, DefaultAssignor &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParIterBase__impl.html',1,'']]],
  ['parmparse_9905',['ParmParse',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParmParse.html',1,'amrex']]],
  ['parser_9906',['Parser',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Parser.html',1,'amrex']]],
  ['parser_5fassign_9907',['parser_assign',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__assign.html',1,'amrex']]],
  ['parser_5ff1_9908',['parser_f1',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__f1.html',1,'amrex']]],
  ['parser_5ff2_9909',['parser_f2',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__f2.html',1,'amrex']]],
  ['parser_5ff3_9910',['parser_f3',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__f3.html',1,'amrex']]],
  ['parser_5fnode_9911',['parser_node',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__node.html',1,'amrex']]],
  ['parser_5fnumber_9912',['parser_number',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__number.html',1,'amrex']]],
  ['parser_5fsymbol_9913',['parser_symbol',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__symbol.html',1,'amrex']]],
  ['parserexeadd_9914',['ParserExeADD',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD.html',1,'amrex']]],
  ['parserexeadd_5fpn_9915',['ParserExeADD_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__PN.html',1,'amrex']]],
  ['parserexeadd_5fpp_9916',['ParserExeADD_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__PP.html',1,'amrex']]],
  ['parserexeadd_5fvn_9917',['ParserExeADD_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__VN.html',1,'amrex']]],
  ['parserexeadd_5fvp_9918',['ParserExeADD_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__VP.html',1,'amrex']]],
  ['parserexecutor_9919',['ParserExecutor',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExecutor.html',1,'amrex']]],
  ['parserexecutor_3c_203_20_3e_9920',['ParserExecutor&lt; 3 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExecutor.html',1,'']]],
  ['parserexediv_5fb_9921',['ParserExeDIV_B',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__B.html',1,'amrex']]],
  ['parserexediv_5ff_9922',['ParserExeDIV_F',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__F.html',1,'amrex']]],
  ['parserexediv_5fpn_9923',['ParserExeDIV_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__PN.html',1,'amrex']]],
  ['parserexediv_5fpp_9924',['ParserExeDIV_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__PP.html',1,'amrex']]],
  ['parserexediv_5fvn_9925',['ParserExeDIV_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__VN.html',1,'amrex']]],
  ['parserexediv_5fvp_9926',['ParserExeDIV_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__VP.html',1,'amrex']]],
  ['parserexef1_9927',['ParserExeF1',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeF1.html',1,'amrex']]],
  ['parserexef2_5fb_9928',['ParserExeF2_B',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeF2__B.html',1,'amrex']]],
  ['parserexef2_5ff_9929',['ParserExeF2_F',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeF2__F.html',1,'amrex']]],
  ['parserexeif_9930',['ParserExeIF',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeIF.html',1,'amrex']]],
  ['parserexejump_9931',['ParserExeJUMP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeJUMP.html',1,'amrex']]],
  ['parserexemul_9932',['ParserExeMUL',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL.html',1,'amrex']]],
  ['parserexemul_5fpn_9933',['ParserExeMUL_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__PN.html',1,'amrex']]],
  ['parserexemul_5fpp_9934',['ParserExeMUL_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__PP.html',1,'amrex']]],
  ['parserexemul_5fvn_9935',['ParserExeMUL_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__VN.html',1,'amrex']]],
  ['parserexemul_5fvp_9936',['ParserExeMUL_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__VP.html',1,'amrex']]],
  ['parserexenull_9937',['ParserExeNull',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeNull.html',1,'amrex']]],
  ['parserexenumber_9938',['ParserExeNumber',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeNumber.html',1,'amrex']]],
  ['parserexepowi_9939',['ParserExePOWI',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExePOWI.html',1,'amrex']]],
  ['parserexesquare_9940',['ParserExeSquare',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSquare.html',1,'amrex']]],
  ['parserexesub_5fb_9941',['ParserExeSUB_B',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__B.html',1,'amrex']]],
  ['parserexesub_5ff_9942',['ParserExeSUB_F',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__F.html',1,'amrex']]],
  ['parserexesub_5fpn_9943',['ParserExeSUB_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__PN.html',1,'amrex']]],
  ['parserexesub_5fpp_9944',['ParserExeSUB_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__PP.html',1,'amrex']]],
  ['parserexesub_5fvn_9945',['ParserExeSUB_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__VN.html',1,'amrex']]],
  ['parserexesub_5fvp_9946',['ParserExeSUB_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__VP.html',1,'amrex']]],
  ['parserexesymbol_9947',['ParserExeSymbol',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSymbol.html',1,'amrex']]],
  ['parserif_9948',['ParserIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1ParserIF.html',1,'amrex::EB2']]],
  ['particle_9949',['Particle',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Particle.html',1,'amrex']]],
  ['particlearray_9950',['ParticleArray',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleArray.html',1,'amrex']]],
  ['particlearrayaccessor_9951',['ParticleArrayAccessor',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleArrayAccessor.html',1,'amrex']]],
  ['particlebase_9952',['ParticleBase',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase.html',1,'amrex']]],
  ['particlebase_3c_20particlereal_2c_20t_5fnreal_2c_200_20_3e_9953',['ParticleBase&lt; ParticleReal, T_NReal, 0 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase.html',1,'']]],
  ['particlebase_3c_20t_2c_200_2c_200_20_3e_9954',['ParticleBase&lt; T, 0, 0 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase_3_01T_00_010_00_010_01_4.html',1,'amrex']]],
  ['particlebase_3c_20t_2c_200_2c_20nint_20_3e_9955',['ParticleBase&lt; T, 0, NInt &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase_3_01T_00_010_00_01NInt_01_4.html',1,'amrex']]],
  ['particlebase_3c_20t_2c_20nreal_2c_200_20_3e_9956',['ParticleBase&lt; T, NReal, 0 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase_3_01T_00_01NReal_00_010_01_4.html',1,'amrex']]],
  ['particlebuffermap_9957',['ParticleBufferMap',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleBufferMap.html',1,'amrex']]],
  ['particlecommdata_9958',['ParticleCommData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCommData.html',1,'amrex']]],
  ['particlecontainer_5fimpl_9959',['ParticleContainer_impl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleContainer__impl.html',1,'amrex']]],
  ['particlecontainer_5fimpl_3c_20t_5fparticletype_2c_200_2c_200_2c_20defaultallocator_2c_20defaultassignor_20_3e_9960',['ParticleContainer_impl&lt; T_ParticleType, 0, 0, DefaultAllocator, DefaultAssignor &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleContainer__impl.html',1,'']]],
  ['particlecontainerbase_9961',['ParticleContainerBase',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleContainerBase.html',1,'amrex']]],
  ['particlecopyop_9962',['ParticleCopyOp',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCopyOp.html',1,'amrex']]],
  ['particlecopyplan_9963',['ParticleCopyPlan',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCopyPlan.html',1,'amrex']]],
  ['particlecpuwrapper_9964',['ParticleCPUWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCPUWrapper.html',1,'amrex']]],
  ['particleidwrapper_9965',['ParticleIDWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleIDWrapper.html',1,'amrex']]],
  ['particleinittype_9966',['ParticleInitType',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleInitType.html',1,'amrex']]],
  ['particlelocator_9967',['ParticleLocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleLocator.html',1,'amrex']]],
  ['particlelocdata_9968',['ParticleLocData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleLocData.html',1,'amrex']]],
  ['particletile_9969',['ParticleTile',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleTile.html',1,'amrex']]],
  ['particletiledata_9970',['ParticleTileData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleTileData.html',1,'amrex']]],
  ['particletiledata_3c_20soaparticlebase_2c_20narrayreal_2c_20narrayint_20_3e_9971',['ParticleTileData&lt; SoAParticleBase, NArrayReal, NArrayInt &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleTileData.html',1,'']]],
  ['pcdata_9972',['PCData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'amrex']]],
  ['pcinterp_9973',['PCInterp',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PCInterp.html',1,'amrex']]],
  ['periodicity_9974',['Periodicity',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Periodicity.html',1,'amrex']]],
  ['persistentifstream_9975',['PersistentIFStream',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1VisMF_1_1PersistentIFStream.html',1,'amrex::VisMF']]],
  ['petscabeclap_9976',['PETScABecLap',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PETScABecLap.html',1,'amrex']]],
  ['physbcfunct_9977',['PhysBCFunct',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PhysBCFunct.html',1,'amrex']]],
  ['physbcfunctnoop_9978',['PhysBCFunctNoOp',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PhysBCFunctNoOp.html',1,'amrex']]],
  ['physbcfunctusecoarseghost_9979',['PhysBCFunctUseCoarseGhost',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PhysBCFunctUseCoarseGhost.html',1,'amrex']]],
  ['pinned_9980',['Pinned',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Gpu_1_1Pinned.html',1,'amrex::Gpu']]],
  ['pinnedarenaallocator_9981',['PinnedArenaAllocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PinnedArenaAllocator.html',1,'amrex']]],
  ['pinnedarenawrapper_9982',['PinnedArenaWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PinnedArenaWrapper.html',1,'amrex']]],
  ['plan_9983',['Plan',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FFT_1_1R2C_1_1Plan.html',1,'amrex::FFT::R2C']]],
  ['plan2_9984',['Plan2',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FFT_1_1R2C_1_1Plan2.html',1,'amrex::FFT::R2C']]],
  ['planeif_9985',['PlaneIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PlaneIF.html',1,'amrex::EB2']]],
  ['plotfiledata_9986',['PlotFileData',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PlotFileData.html',1,'amrex']]],
  ['plotfiledataimpl_9987',['PlotFileDataImpl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PlotFileDataImpl.html',1,'amrex']]],
  ['plus_9988',['Plus',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Plus.html',1,'amrex']]],
  ['podvector_9989',['PODVector',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3aassigngrid_3c_20biniteratorfactory_20_3e_20_3e_9990',['PODVector&lt; amrex::AssignGrid&lt; BinIteratorFactory &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20amrex_3a_3aboxnd_20_3e_9991',['PODVector&lt; amrex::BoxND &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20amrex_3a_3agpuarray_3c_20amrex_3a_3amlcelllinopt_3a_3abctl_2c_202_20_2aamrex_5fspacedim_20_3e_20_3e_9992',['PODVector&lt; amrex::GpuArray&lt; amrex::MLCellLinOpT::BCTL, 2 *AMREX_SPACEDIM &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20amrex_3a_3aneighborcode_20_3e_9993',['PODVector&lt; amrex::NeighborCode &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20amrex_3a_3aopenbc_3a_3amomtag_20_3e_9994',['PODVector&lt; amrex::openbc::MomTag &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20amrex_3a_3astltools_3a_3abvhnodet_20_3e_9995',['PODVector&lt; amrex::STLtools::BVHNodeT &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20amrex_3a_3astltools_3a_3atriangle_20_3e_9996',['PODVector&lt; amrex::STLtools::Triangle &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20amrex_3a_3axdim3_20_3e_9997',['PODVector&lt; amrex::XDim3 &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20boxnd_3c_20amrex_5fspacedim_20_3e_20_3e_9998',['PODVector&lt; BoxND&lt; AMREX_SPACEDIM &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20char_20_3e_9999',['PODVector&lt; char &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20char_2c_20amrex_3a_3apolymorphicarenaallocator_3c_20char_20_3e_20_3e_10000',['PODVector&lt; char, amrex::PolymorphicArenaAllocator&lt; char &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20const_20int_20_2a_20_3e_10001',['PODVector&lt; const int * &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20const_20int_20_2a_2c_20allocator_3c_20const_20int_20_2a_20_3e_20_3e_10002',['PODVector&lt; const int *, Allocator&lt; const int * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20const_20int_20_2a_2c_20defaultallocator_3c_20const_20int_20_2a_20_3e_20_3e_10003',['PODVector&lt; const int *, DefaultAllocator&lt; const int * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20const_20particlereal_20_2a_20_3e_10004',['PODVector&lt; const ParticleReal * &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20const_20particlereal_20_2a_2c_20allocator_3c_20const_20particlereal_20_2a_20_3e_20_3e_10005',['PODVector&lt; const ParticleReal *, Allocator&lt; const ParticleReal * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20const_20particlereal_20_2a_2c_20defaultallocator_3c_20const_20particlereal_20_2a_20_3e_20_3e_10006',['PODVector&lt; const ParticleReal *, DefaultAllocator&lt; const ParticleReal * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20index_5ftype_20_3e_10007',['PODVector&lt; index_type &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20int_20_2a_20_3e_10008',['PODVector&lt; int * &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20int_20_2a_2c_20allocator_3c_20int_20_2a_20_3e_20_3e_10009',['PODVector&lt; int *, Allocator&lt; int * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20int_20_2a_2c_20defaultallocator_3c_20int_20_2a_20_3e_20_3e_10010',['PODVector&lt; int *, DefaultAllocator&lt; int * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20int_20_3e_10011',['PODVector&lt; int &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20node_20_3e_10012',['PODVector&lt; Node &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20particlereal_20_2a_20_3e_10013',['PODVector&lt; ParticleReal * &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20particlereal_20_2a_2c_20allocator_3c_20particlereal_20_2a_20_3e_20_3e_10014',['PODVector&lt; ParticleReal *, Allocator&lt; ParticleReal * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20particlereal_20_2a_2c_20defaultallocator_3c_20particlereal_20_2a_20_3e_20_3e_10015',['PODVector&lt; ParticleReal *, DefaultAllocator&lt; ParticleReal * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20particletype_2c_20allocator_3c_20particletype_20_3e_20_3e_10016',['PODVector&lt; ParticleType, Allocator&lt; ParticleType &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20particletype_2c_20defaultallocator_3c_20particletype_20_3e_20_3e_10017',['PODVector&lt; ParticleType, DefaultAllocator&lt; ParticleType &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20std_3a_3asize_5ft_20_3e_10018',['PODVector&lt; std::size_t &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20uint64_5ft_2c_20allocator_3c_20uint64_5ft_20_3e_20_3e_10019',['PODVector&lt; uint64_t, Allocator&lt; uint64_t &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20uint64_5ft_2c_20defaultallocator_3c_20uint64_5ft_20_3e_20_3e_10020',['PODVector&lt; uint64_t, DefaultAllocator&lt; uint64_t &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20unsigned_20int_20_3e_10021',['PODVector&lt; unsigned int &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['poisson_10022',['Poisson',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1FFT_1_1Poisson.html',1,'amrex::FFT']]],
  ['poissonhybrid_10023',['PoissonHybrid',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1FFT_1_1PoissonHybrid.html',1,'amrex::FFT']]],
  ['polarb_10024',['PolarB',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1PolarB.html',1,'amrex::FabArrayBase']]],
  ['poly_5feval_10025',['poly_eval',['https://amrex-codes.github.io/amrex/doxygen/interfacesdcquadrature__mod_1_1poly__eval.html',1,'sdcquadrature_mod']]],
  ['polyif_10026',['PolyIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PolyIF.html',1,'amrex::EB2']]],
  ['polymorphicarenaallocator_10027',['PolymorphicArenaAllocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PolymorphicArenaAllocator.html',1,'amrex']]],
  ['polymorphicarenawrapper_10028',['PolymorphicArenaWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PolymorphicArenaWrapper.html',1,'amrex']]],
  ['polymorphicarray4_10029',['PolymorphicArray4',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PolymorphicArray4.html',1,'amrex']]],
  ['polynomialif_10030',['PolynomialIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PolynomialIF.html',1,'amrex::EB2']]],
  ['polyterm_10031',['PolyTerm',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PolyTerm.html',1,'amrex::EB2']]],
  ['poststagenoop_10032',['PostStageNoOp',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RungeKutta_1_1PostStageNoOp.html',1,'amrex::RungeKutta']]],
  ['pp_5fentry_10033',['PP_entry',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParmParse_1_1PP__entry.html',1,'amrex::ParmParse']]],
  ['print_10034',['Print',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Print.html',1,'amrex']]],
  ['printtofile_10035',['PrintToFile',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PrintToFile.html',1,'amrex']]],
  ['process_5ftopology_5ft_10036',['process_topology_t',['https://amrex-codes.github.io/amrex/doxygen/structprocess__topology__t.html',1,'']]],
  ['processteam_10037',['ProcessTeam',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParallelDescriptor_1_1ProcessTeam.html',1,'amrex::ParallelDescriptor']]],
  ['procstats_10038',['ProcStats',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1TinyProfiler_1_1ProcStats.html',1,'amrex::TinyProfiler']]],
  ['psicode_10039',['PsiCode',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1algoim_1_1PsiCode.html',1,'amrex::algoim']]]
];
