var searchData=
[
  ['r2c_10188',['R2C',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1FFT_1_1R2C.html',1,'amrex::FFT']]],
  ['r2c_3c_20t_20_3e_10189',['R2C&lt; T &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1FFT_1_1R2C.html',1,'amrex::FFT']]],
  ['r2x_10190',['R2X',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1FFT_1_1R2X.html',1,'amrex::FFT']]],
  ['randomengine_10191',['RandomEngine',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RandomEngine.html',1,'amrex']]],
  ['range_5fimpl_10192',['range_impl',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Gpu_1_1range__detail_1_1range__impl.html',1,'amrex::Gpu::range_detail']]],
  ['rb180_10193',['RB180',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1RB180.html',1,'amrex::FabArrayBase']]],
  ['rb90_10194',['RB90',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1RB90.html',1,'amrex::FabArrayBase']]],
  ['realbox_10195',['RealBox',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1RealBox.html',1,'amrex']]],
  ['realdescriptor_10196',['RealDescriptor',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1RealDescriptor.html',1,'amrex']]],
  ['realvect_10197',['RealVect',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1RealVect.html',1,'amrex']]],
  ['redistributeunpackpolicy_10198',['RedistributeUnpackPolicy',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RedistributeUnpackPolicy.html',1,'amrex']]],
  ['reducedata_10199',['ReduceData',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ReduceData.html',1,'amrex']]],
  ['reduceoplogicaland_10200',['ReduceOpLogicalAnd',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpLogicalAnd.html',1,'amrex']]],
  ['reduceoplogicalor_10201',['ReduceOpLogicalOr',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpLogicalOr.html',1,'amrex']]],
  ['reduceopmax_10202',['ReduceOpMax',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpMax.html',1,'amrex']]],
  ['reduceopmin_10203',['ReduceOpMin',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpMin.html',1,'amrex']]],
  ['reduceops_10204',['ReduceOps',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ReduceOps.html',1,'amrex']]],
  ['reduceopsum_10205',['ReduceOpSum',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpSum.html',1,'amrex']]],
  ['reductionentry_10206',['ReductionEntry',['https://amrex-codes.github.io/amrex/doxygen/structCommProfStats_1_1ReductionEntry.html',1,'CommProfStats']]],
  ['ref_10207',['Ref',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1AlgPartition_1_1Ref.html',1,'amrex::AlgPartition::Ref'],['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1DistributionMapping_1_1Ref.html',1,'amrex::DistributionMapping::Ref']]],
  ['ref_5fwrapper_10208',['ref_wrapper',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ref__wrapper.html',1,'amrex']]],
  ['refid_10209',['RefID',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1BoxArray_1_1RefID.html',1,'amrex::BoxArray::RefID'],['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1DistributionMapping_1_1RefID.html',1,'amrex::DistributionMapping::RefID']]],
  ['regionsprofstats_10210',['RegionsProfStats',['https://amrex-codes.github.io/amrex/doxygen/classRegionsProfStats.html',1,'']]],
  ['regiontag_10211',['RegionTag',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1RegionTag.html',1,'amrex::FabArrayBase']]],
  ['retsum_10212',['RetSum',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Scan_1_1RetSum.html',1,'amrex::Scan']]],
  ['rkintegrator_10213',['RKIntegrator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1RKIntegrator.html',1,'amrex']]],
  ['rotatebwd_10214',['RotateBwd',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FFT_1_1RotateBwd.html',1,'amrex::FFT']]],
  ['rotatefwd_10215',['RotateFwd',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FFT_1_1RotateFwd.html',1,'amrex::FFT']]],
  ['rotationif_10216',['RotationIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1RotationIF.html',1,'amrex::EB2']]],
  ['runongpu_10217',['RunOnGpu',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu.html',1,'amrex']]],
  ['runongpu_3c_20arenaallocator_3c_20t_20_3e_20_3e_10218',['RunOnGpu&lt; ArenaAllocator&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu_3_01ArenaAllocator_3_01T_01_4_01_4.html',1,'amrex']]],
  ['runongpu_3c_20asyncarenaallocator_3c_20t_20_3e_20_3e_10219',['RunOnGpu&lt; AsyncArenaAllocator&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu_3_01AsyncArenaAllocator_3_01T_01_4_01_4.html',1,'amrex']]],
  ['runongpu_3c_20devicearenaallocator_3c_20t_20_3e_20_3e_10220',['RunOnGpu&lt; DeviceArenaAllocator&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu_3_01DeviceArenaAllocator_3_01T_01_4_01_4.html',1,'amrex']]],
  ['runongpu_3c_20managedarenaallocator_3c_20t_20_3e_20_3e_10221',['RunOnGpu&lt; ManagedArenaAllocator&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu_3_01ManagedArenaAllocator_3_01T_01_4_01_4.html',1,'amrex']]]
];
